### ISSUE TITLE
Empty message

### ISSUE THREAD

**Issue by RE4ERKA** [jandie1505/HealthManager2#1]
I removed the text from the config because I need the player to not show anything in the chat after that, I am shown an empty message instead of not showing anything.
![image](https://user-images.githubusercontent.com/66727581/114517487-96795d00-9c68-11eb-8e7a-23903ff29c96.png)
Also, is it possible to make the commands available via the console? It's not as important as the problem above, but still.

**Comment by jandie1505** [comment]
Do you mean this messages (target messages)?
These can be disabled in the config with the option "sendmessagestotarget" (set it to false).
![image](https://user-images.githubusercontent.com/34031551/114553894-6a5cdc80-9c66-11eb-8ae6-79b143bc9350.png)
However, I will include the feature in an upcoming update that the message will no longer be displayed when it is empty.
I will also include in an upcoming update that the commands can be executed via the console, probably I will change the commands to CommandAPICommands.

**Comment by RE4ERKA** [comment]
Yes, I can use the "sendmessagestotarget" option, but I give out health through the player itself, which seems to be an operator (I do this through the plugin on the menu). I have to do this because the commands via the console do not work.
If the player changes his health by writing a command, then an empty message is shown to him.
But thanks anyway. This will help me. I will wait for the next update.

**Comment by jandie1505** [comment]
The commands can now also be executed from the console. The other features will come in an upcoming update.
https://github.com/jandie1505/HealthManager2/releases/download/2.5/HealthManager2.jar
I will close this issue if the empty messages are fixed.

**Comment by jandie1505** [comment]
Chat messages are now no longer displayed if they are empty in the config.
https://github.com/jandie1505/HealthManager2/releases/tag/2.6
This issue is now closed.
If you have any suggestions for the plugin, feel free to let me know.
